version: "3.7"

services:
  wdb:
    image: kozea/wdb:3.3.0
    ports: ["1984:1984"]
    restart: unless-stopped
    networks:
      - nl-g2p-odoonet
    depends_on: ["db"]
  # ------------------------

  odoo:
    volumes:
      # Host paths (odoo modules, src code & conf)
      - ./custom:${ODOO_EXTRA_ADDONS}:delegated
    environment:
      - LOG_LEVEL=debug
      - WITHOUT_DEMO=False
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_WEB_PORT=1984
      - DEBUGPY_ENABLE=1
      - WORKERS=2
      - ODOO_QUEUE_JOB_PORT=8069
      - ODOO_QUEUE_JOB_CHANNELS=root:4
    depends_on: ["db", "wdb"]
    command: ["odoo", "--dev", "--load=wdb,reload,qweb,werkzeug,xml,web,queue_job", "--log-handler=odoo.addons.queue_job:DEBUG", "--workers=2"]
