version: "3.7"

networks:
  default:
    external:
      name: cloudbuild
  nl-g2p-odoonet:

volumes:
  nl-g2p-odoo-data:
  nl-g2p-odoo-testlogs:
  nl-g2p-odoo-modules:
  nl-g2p-psql:

services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8068:80"
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - odoo
    links:
      - odoo:odoo
    networks:
      nl-g2p-odoonet:
  odoo:
    image: newlogic42/dockerdoo:${ODOO_VERSION}
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (.ssh configuration)
      - ~/.ssh/:/opt/odoo/.ssh/:cached
      # Named volumes
      - nl-g2p-odoo-data:${ODOO_DATA_DIR}
      - nl-g2p-odoo-testlogs:${ODOO_LOGS_DIR}
      - nl-g2p-odoo-modules:${ODOO_EXTRA_ADDONS}
    depends_on:
      - db

    networks:
      nl-g2p-odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - nl-g2p-psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      nl-g2p-odoonet:
